%% run anova on subject means

%DATA(isub).distfromlowasspass(1).sorted_data(cond).goodpitchdata_difflowpassfilt
for isub=1:27
sub(isub).clear_std=[...
nanstd(DATA(isub).distfromlowasspass.sorted_data(1).goodpitchdata_difflowpassfilt) ...
nanstd(DATA(isub).distfromlowasspass.sorted_data(2).goodpitchdata_difflowpassfilt) ...
nanstd(DATA(isub).distfromlowasspass.sorted_data(3).goodpitchdata_difflowpassfilt) ...
nanstd(DATA(isub).distfromlowasspass.sorted_data(4).goodpitchdata_difflowpassfilt) ...
nanstd(DATA(isub).distfromlowasspass.sorted_data(5).goodpitchdata_difflowpassfilt)];

sub(isub).noise_std=[...
nanstd(DATA(isub).distfromlowasspass.sorted_data(6).goodpitchdata_difflowpassfilt) ...
nanstd(DATA(isub).distfromlowasspass.sorted_data(7).goodpitchdata_difflowpassfilt) ...
nanstd(DATA(isub).distfromlowasspass.sorted_data(8).goodpitchdata_difflowpassfilt) ...
nanstd(DATA(isub).distfromlowasspass.sorted_data(9).goodpitchdata_difflowpassfilt) ...
nanstd(DATA(isub).distfromlowasspass.sorted_data(10).goodpitchdata_difflowpassfilt)];
end

anovadata_stdev=[ ...
            sub(1).clear_std sub(2).clear_std sub(3).clear_std ...
            sub(4).clear_std sub(5).clear_std sub(6).clear_std ...
            sub(7).clear_std sub(8).clear_std sub(9).clear_std ...
            sub(10).clear_std sub(11).clear_std sub(12).clear_std ...
            sub(13).clear_std sub(14).clear_std sub(15).clear_std ...
            sub(16).clear_std sub(17).clear_std sub(18).clear_std ...
            sub(19).clear_std sub(20).clear_std sub(21).clear_std ...
            sub(22).clear_std sub(23).clear_std sub(24).clear_std ...
            sub(25).clear_std sub(26).clear_std sub(27).clear_std ...
            sub(1).noise_std sub(2).noise_std sub(3).noise_std ...
            sub(4).noise_std sub(5).noise_std sub(6).noise_std ...
            sub(7).noise_std sub(8).noise_std sub(9).noise_std ...
            sub(10).noise_std sub(11).noise_std sub(12).noise_std ...
            sub(13).noise_std sub(14).noise_std sub(15).noise_std ...
            sub(16).noise_std sub(17).noise_std sub(18).noise_std ...
            sub(19).noise_std sub(20).noise_std sub(21).noise_std ...
            sub(22).noise_std sub(23).noise_std sub(24).noise_std ...
            sub(25).noise_std sub(26).noise_std sub(27).noise_std];
        
        
% length(anovadata)  202770      

test=ones(1,60080);
test2=ones(1,41305);
test2=test2*2;
subjectgroup=[test test2 test test2];
%subjects = [1 2 3 4 5 6 7 8]; % Assuming that subjects 1-4 were in group 1 and 5-8 were in group 2

%create condition group
condition = cell(1,202770);
for i=1:101385
    condition{i}='clear';
end
for i=101386:101385*2
    condition{i}='noise';
end
condition=condition';

group1=[subjectgroup];
group2=[condition];
p = anovan(anovadata_stdev,{group1 group2},'model','interaction')

        
        
        
        