%% Check stdev of grp for elimination of bad trials:------------------------
% ZKA August 2014

clear all
cd /Users/zagnew/Cereb_data/data_final_run/GroupData
load /Users/zagnew/Cereb_data/data_final_run/GroupData/GroupData.mat

% only looks at the subjects included. this is created in the previous
% script. (i.e. GroupData.WT_patC1_pre is only the good subs) 
Gp_stwithin.allsubs_allconds_pre_pats= [nanmean(GroupData.WT_patC1_pre) nanmean(GroupData.WT_patC2_pre) ...
    nanmean(GroupData.WT_patC3_pre) nanmean(GroupData.WT_patC4_pre) ...
    nanmean(GroupData.WT_patC4_pre) nanmean(GroupData.WT_patC6_pre) ...
    nanmean(GroupData.WT_patC5_pre) nanmean(GroupData.WT_patC8_pre) ...
    nanmean(GroupData.WT_patC9_pre) nanmean(GroupData.WT_patC10_pre)];
    
Gp_stwithin.allsubs_allconds_pre_HCs=[nanmean(GroupData.WT_HCC1_pre) nanmean(GroupData.WT_HCC2_pre) ...
    nanmean(GroupData.WT_HCC3_pre) nanmean(GroupData.WT_HCC4_pre) ...
    nanmean(GroupData.WT_HCC4_pre) nanmean(GroupData.WT_HCC6_pre) ...
    nanmean(GroupData.WT_HCC5_pre) nanmean(GroupData.WT_HCC8_pre) ...
    nanmean(GroupData.WT_HCC9_pre) nanmean(GroupData.WT_HCC10_pre)];

Gp_stwithin.allsubs_allconds_post_pats=[nanmean(GroupData.WT_patC1_post) nanmean(GroupData.WT_patC2_post) ...
    nanmean(GroupData.WT_patC3_post) nanmean(GroupData.WT_patC4_post) ...
    nanmean(GroupData.WT_patC4_post) nanmean(GroupData.WT_patC6_post) ...
    nanmean(GroupData.WT_patC5_post) nanmean(GroupData.WT_patC8_post) ...
    nanmean(GroupData.WT_patC9_post) nanmean(GroupData.WT_patC10_post)];

Gp_stwithin.allsubs_allconds_post_HCs=[nanmean(GroupData.WT_HCC1_post) nanmean(GroupData.WT_HCC2_post) ...
    nanmean(GroupData.WT_HCC3_post) nanmean(GroupData.WT_HCC4_post) ...
    nanmean(GroupData.WT_HCC4_post) nanmean(GroupData.WT_HCC6_post) ...
    nanmean(GroupData.WT_HCC5_post) nanmean(GroupData.WT_HCC8_post) ...
    nanmean(GroupData.WT_HCC9_post) nanmean(GroupData.WT_HCC10_post)];


Gp_stwithin.allsubs_allconds_wholetrial_pats=[nanmean(GroupData.WT_patC1_wholetrial) nanmean(GroupData.WT_patC2_wholetrial) ...
    nanmean(GroupData.WT_patC3_wholetrial) nanmean(GroupData.WT_patC4_wholetrial) ...
    nanmean(GroupData.WT_patC4_wholetrial) nanmean(GroupData.WT_patC6_wholetrial) ...
    nanmean(GroupData.WT_patC5_wholetrial) nanmean(GroupData.WT_patC8_wholetrial) ...
    nanmean(GroupData.WT_patC9_wholetrial) nanmean(GroupData.WT_patC10_wholetrial)];

Gp_stwithin.allsubs_allconds_wholetrial_HCs=[nanmean(GroupData.WT_HCC1_wholetrial) nanmean(GroupData.WT_HCC2_wholetrial) ...
    nanmean(GroupData.WT_HCC3_wholetrial) nanmean(GroupData.WT_HCC4_wholetrial) ...
    nanmean(GroupData.WT_HCC4_wholetrial) nanmean(GroupData.WT_HCC6_wholetrial) ...
    nanmean(GroupData.WT_HCC5_wholetrial) nanmean(GroupData.WT_HCC8_wholetrial) ...
    nanmean(GroupData.WT_HCC9_wholetrial) nanmean(GroupData.WT_HCC10_wholetrial)];

Gp_stwithin.final_pre_pats=nanmean(Gp_stwithin.allsubs_allconds_pre_pats);
Gp_stwithin.final_post_pats=nanmean(Gp_stwithin.allsubs_allconds_post_pats);
Gp_stwithin.final_wholetrial_pats=nanmean(Gp_stwithin.allsubs_allconds_wholetrial_pats);

Gp_stwithin.final_pre_to_exlude_pats=2*Gp_stwithin.final_pre_pats
Gp_stwithin.final_post_to_exlude_pats=2*Gp_stwithin.final_post_pats
Gp_stwithin.final_wholetrial_to_exlude_pats=2*Gp_stwithin.final_wholetrial_pats

Gp_stwithin.final_pre_HCs=nanmean(Gp_stwithin.allsubs_allconds_pre_HCs);
Gp_stwithin.final_post_HCs=nanmean(Gp_stwithin.allsubs_allconds_post_HCs);
Gp_stwithin.final_wholetrial_HCs=nanmean(Gp_stwithin.allsubs_allconds_wholetrial_HCs);

Gp_stwithin.final_pre_to_exlude_HCs=2*Gp_stwithin.final_pre_HCs
Gp_stwithin.final_post_to_exlude_HCs=2*Gp_stwithin.final_post_HCs
Gp_stwithin.final_wholetrial_to_exlude_HCs=2*Gp_stwithin.final_wholetrial_HCs


% ---------- amplitude



Gp_stwithin.allsubs_allconds_pre_AMP_pats=[nanmean(GroupData.WT_patC1_pre_AMP) nanmean(GroupData.WT_patC2_pre_AMP) ...
    nanmean(GroupData.WT_patC3_pre_AMP) nanmean(GroupData.WT_patC4_pre_AMP) ...
    nanmean(GroupData.WT_patC4_pre_AMP) nanmean(GroupData.WT_patC6_pre_AMP) ...
    nanmean(GroupData.WT_patC5_pre_AMP) nanmean(GroupData.WT_patC8_pre_AMP) ...
    nanmean(GroupData.WT_patC9_pre_AMP) nanmean(GroupData.WT_patC10_pre_AMP)];

Gp_stwithin.allsubs_allconds_pre_AMP_HCs=[nanmean(GroupData.WT_HCC1_pre_AMP) nanmean(GroupData.WT_HCC2_pre_AMP) ...
    nanmean(GroupData.WT_HCC3_pre_AMP) nanmean(GroupData.WT_HCC4_pre_AMP) ...
    nanmean(GroupData.WT_HCC4_pre_AMP) nanmean(GroupData.WT_HCC6_pre_AMP) ...
    nanmean(GroupData.WT_HCC5_pre_AMP) nanmean(GroupData.WT_HCC8_pre_AMP) ...
    nanmean(GroupData.WT_HCC9_pre_AMP) nanmean(GroupData.WT_HCC10_pre_AMP)];

Gp_stwithin.allsubs_allconds_post_AMP_pats=[nanmean(GroupData.WT_patC1_post_AMP) nanmean(GroupData.WT_patC2_post_AMP) ...
    nanmean(GroupData.WT_patC3_post_AMP) nanmean(GroupData.WT_patC4_post_AMP) ...
    nanmean(GroupData.WT_patC4_post_AMP) nanmean(GroupData.WT_patC6_post_AMP) ...
    nanmean(GroupData.WT_patC5_post_AMP) nanmean(GroupData.WT_patC8_post_AMP) ...
    nanmean(GroupData.WT_patC9_post_AMP) nanmean(GroupData.WT_patC10_post_AMP)];

Gp_stwithin.allsubs_allconds_post_AMP_HCs=[nanmean(GroupData.WT_HCC1_post_AMP) nanmean(GroupData.WT_HCC2_post_AMP) ...
    nanmean(GroupData.WT_HCC3_post_AMP) nanmean(GroupData.WT_HCC4_post_AMP) ...
    nanmean(GroupData.WT_HCC4_post_AMP) nanmean(GroupData.WT_HCC6_post_AMP) ...
    nanmean(GroupData.WT_HCC5_post_AMP) nanmean(GroupData.WT_HCC8_post_AMP) ...
    nanmean(GroupData.WT_HCC9_post_AMP) nanmean(GroupData.WT_HCC10_post_AMP)];


Gp_stwithin.allsubs_allconds_wholetrial_AMP_pats=[nanmean(GroupData.WT_patC1_wholetrial_AMP) nanmean(GroupData.WT_patC2_wholetrial_AMP) ...
    nanmean(GroupData.WT_patC3_wholetrial_AMP) nanmean(GroupData.WT_patC4_wholetrial_AMP) ...
    nanmean(GroupData.WT_patC4_wholetrial_AMP) nanmean(GroupData.WT_patC6_wholetrial_AMP) ...
    nanmean(GroupData.WT_patC5_wholetrial_AMP) nanmean(GroupData.WT_patC8_wholetrial_AMP) ...
    nanmean(GroupData.WT_patC9_wholetrial_AMP) nanmean(GroupData.WT_patC10_wholetrial_AMP)];

Gp_stwithin.allsubs_allconds_wholetrial_AMP_HCs=[nanmean(GroupData.WT_HCC1_wholetrial_AMP) nanmean(GroupData.WT_HCC2_wholetrial_AMP) ...
    nanmean(GroupData.WT_HCC3_wholetrial_AMP) nanmean(GroupData.WT_HCC4_wholetrial_AMP) ...
    nanmean(GroupData.WT_HCC4_wholetrial_AMP) nanmean(GroupData.WT_HCC6_wholetrial_AMP) ...
    nanmean(GroupData.WT_HCC5_wholetrial_AMP) nanmean(GroupData.WT_HCC8_wholetrial_AMP) ...
    nanmean(GroupData.WT_HCC9_wholetrial_AMP) nanmean(GroupData.WT_HCC10_wholetrial_AMP)];

Gp_stwithin.final_pre_AMP_pats=nanmean(Gp_stwithin.allsubs_allconds_pre_AMP_pats);
Gp_stwithin.final_post_AMP_pats=nanmean(Gp_stwithin.allsubs_allconds_post_AMP_pats);
Gp_stwithin.final_wholetrial_AMP_pats=nanmean(Gp_stwithin.allsubs_allconds_wholetrial_AMP_pats);

Gp_stwithin.final_pre_AMP_to_exlude_AMP_pats=2*Gp_stwithin.final_pre_AMP_pats
Gp_stwithin.final_post_AMP_to_exlude_AMP_pats=2*Gp_stwithin.final_post_AMP_pats
Gp_stwithin.final_wholetrial_AMP_to_exlude_AMP_pats=2*Gp_stwithin.final_wholetrial_AMP_pats

Gp_stwithin.final_pre_AMP_HCs=nanmean(Gp_stwithin.allsubs_allconds_pre_AMP_HCs);
Gp_stwithin.final_post_AMP_HCs=nanmean(Gp_stwithin.allsubs_allconds_post_AMP_HCs);
Gp_stwithin.final_wholetrial_AMP_HCs=nanmean(Gp_stwithin.allsubs_allconds_wholetrial_AMP_HCs);

Gp_stwithin.final_pre_AMP_to_exlude_AMP_HCs=2*Gp_stwithin.final_pre_AMP_HCs
Gp_stwithin.final_post_AMP_to_exlude_AMP_HCs=2*Gp_stwithin.final_post_AMP_HCs
Gp_stwithin.final_wholetrial_AMP_to_exlude_AMP_HCs=2*Gp_stwithin.final_wholetrial_AMP_HCs

 
% final_pre_to_exlude_pats: 85.9509
% final_post_to_exlude_pats: 77.5966
% final_wholetrial_to_exlude_pats: 231.7634
% final_pre_to_exlude_HCs: 28.9987
% final_post_to_exlude_HCs: 24.7198
% final_wholetrial_to_exlude_HCs: 138.8496
% 
% final_pre_AMP_to_exlude_AMP_pats: 2.1613e+08
% final_post_AMP_to_exlude_AMP_pats: 1.6914e+08
% final_wholetrial_AMP_to_exlude_AMP_pats: 8.7689e+07
% final_pre_AMP_to_exlude_AMP_HCs: 1.6009e+08
% final_post_AMP_to_exlude_AMP_HCs: 1.1635e+08
% final_wholetrial_AMP_to_exlude_AMP_HCs: 5.2952e+08

     
     
     