%% called from E_calcfromlowpass
% 3. WT mean and std - calculates on each trial and takes the average of
% that. 

for ipat=1:numpats
    for icond=1:10
        for itrial=1:8
            GpStd_WT_PAT(ipat).data(icond).data(itrial)=nanstd(DATA_DIST(ipat).distfromlowasspass(1).sorted_data(icond).goodpitchdata_difflowpassfilt(itrial,:));
            GpMean_WT_PAT(ipat).data(icond).data(itrial)=nanmean(DATA_DIST(ipat).distfromlowasspass(1).sorted_data(icond).goodpitchdata_difflowpassfilt(itrial,:));
        end
    end
end

for isub=1:numHCs
    for icond=1:10
        for itrial=1:8
            GpStd_WT_HC(isub).data(icond).data(itrial)=nanstd(DATA_DIST(isub+numpats).distfromlowasspass(1).sorted_data(icond).goodpitchdata_difflowpassfilt(itrial,:));
            GpMean_WT_HC(isub).data(icond).data(itrial)=nanmean(DATA_DIST(isub+numpats).distfromlowasspass(1).sorted_data(icond).goodpitchdata_difflowpassfilt(itrial,:));
        end
    end
end

for icond=1:5
PatGp_WTstddev_clear(icond,:)=horzcat(...
    GpStd_WT_PAT(1).data(icond).data, GpStd_WT_PAT(2).data(icond).data, ...
    GpStd_WT_PAT(3).data(icond).data, GpStd_WT_PAT(4).data(icond).data, ...
    GpStd_WT_PAT(5).data(icond).data, GpStd_WT_PAT(6).data(icond).data, ...
    GpStd_WT_PAT(7).data(icond).data, GpStd_WT_PAT(8).data(icond).data, ...
    GpStd_WT_PAT(9).data(icond).data, GpStd_WT_PAT(10).data(icond).data, ...
    GpStd_WT_PAT(11).data(icond).data);
%     , GpStd_WT_PAT(12).data(icond).data, ...
%     GpStd_WT_PAT(13).data(icond).data, GpStd_WT_PAT(14).data(icond).data, ...
%     GpStd_WT_PAT(15).data(icond).data, GpStd_WT_PAT(16).data(icond).data);
PatGp_WT_meandev_clear(icond,:)=horzcat(...
    GpStd_WT_PAT(1).data(icond).data, GpMean_WT_PAT(2).data(icond).data, ...
    GpMean_WT_PAT(3).data(icond).data, GpMean_WT_PAT(4).data(icond).data, ...
    GpMean_WT_PAT(5).data(icond).data, GpMean_WT_PAT(6).data(icond).data, ...
    GpMean_WT_PAT(7).data(icond).data, GpMean_WT_PAT(8).data(icond).data, ...
    GpMean_WT_PAT(9).data(icond).data, GpMean_WT_PAT(10).data(icond).data, ...
    GpMean_WT_PAT(11).data(icond).data);
end

PatGp_WTstddev_clear_horz=horzcat(...
    PatGp_WTstddev_clear(1,:), PatGp_WTstddev_clear (2,:), ...
    PatGp_WTstddev_clear(3,:), PatGp_WTstddev_clear (4,:), ...
    PatGp_WTstddev_clear(5,:));

PatGp_WT_mean_clear_horz=horzcat(...
    PatGp_WT_meandev_clear(1,:), PatGp_WT_meandev_clear (2,:), ...
    PatGp_WT_meandev_clear(3,:), PatGp_WT_meandev_clear (4,:), ...
    PatGp_WT_meandev_clear(5,:));

for icond=1:5
PatGp_WTstddev_noise(icond,:)=horzcat(...
    GpStd_WT_PAT(1).data(icond+5).data, GpStd_WT_PAT(2).data(icond+5).data, ...
    GpStd_WT_PAT(3).data(icond+5).data, GpStd_WT_PAT(4).data(icond+5).data, ...
    GpStd_WT_PAT(5).data(icond+5).data, GpStd_WT_PAT(6).data(icond+5).data, ...
    GpStd_WT_PAT(7).data(icond+5).data, GpStd_WT_PAT(8).data(icond+5).data, ...
    GpStd_WT_PAT(9).data(icond+5).data, GpStd_WT_PAT(10).data(icond+5).data, ...
    GpStd_WT_PAT(11).data(icond+5).data); 
%     , GpStd_WT_PAT(12).data(icond+5).data, ...
%     GpStd_WT_PAT(13).data(icond+5).data, GpStd_WT_PAT(14).data(icond+5).data, ...
%     GpStd_WT_PAT(15).data(icond+5).data, GpStd_WT_PAT(16).data(icond+5).data);

PatGp_WT_mean_noise(icond,:)=horzcat(...
    GpMean_WT_PAT(1).data(icond+5).data, GpMean_WT_PAT(2).data(icond+5).data, ...
    GpMean_WT_PAT(3).data(icond+5).data, GpMean_WT_PAT(4).data(icond+5).data, ...
    GpMean_WT_PAT(5).data(icond+5).data, GpMean_WT_PAT(6).data(icond+5).data, ...
    GpMean_WT_PAT(7).data(icond+5).data, GpMean_WT_PAT(8).data(icond+5).data, ...
    GpMean_WT_PAT(9).data(icond+5).data, GpMean_WT_PAT(10).data(icond+5).data, ...
    GpMean_WT_PAT(11).data(icond+5).data); 
end

PatGp_WTstddev_noise_horz=horzcat(...
    PatGp_WTstddev_noise(1,:), PatGp_WTstddev_noise (2,:), ...
    PatGp_WTstddev_noise(3,:), PatGp_WTstddev_noise (4,:), ...
    PatGp_WTstddev_noise(5,:));

PatGp_WT_mean_noise_horz=horzcat(...
    PatGp_WT_mean_noise(1,:), PatGp_WT_mean_noise (2,:), ...
    PatGp_WT_mean_noise(3,:), PatGp_WT_mean_noise (4,:), ...
    PatGp_WT_mean_noise(5,:));


for icond=1:5
HCGp_WTstddev_clear(icond,:)=horzcat(...
    GpStd_WT_HC(1).data(icond).data, GpStd_WT_HC(2).data(icond).data, ...
    GpStd_WT_HC(3).data(icond).data, GpStd_WT_HC(4).data(icond).data);
%     , ...
%     GpStd_WT_HC(5).data(icond).data, GpStd_WT_HC(6).data(icond).data, ...
%     GpStd_WT_HC(7).data(icond).data, GpStd_WT_HC(8).data(icond).data, ...
%     GpStd_WT_HC(9).data(icond).data, GpStd_WT_HC(10).data(icond).data, ...
%     GpStd_WT_HC(11).data(icond).data);
HCGp_WT_mean_clear(icond,:)=horzcat(...
    GpMean_WT_HC(1).data(icond).data, GpMean_WT_HC(2).data(icond).data, ...
    GpMean_WT_HC(3).data(icond).data, GpMean_WT_HC(4).data(icond).data);

end

HCGp_WTstddev_clear_horz=horzcat(...
    HCGp_WTstddev_clear(1,:), HCGp_WTstddev_clear (2,:), ...
    HCGp_WTstddev_clear(3,:), HCGp_WTstddev_clear (4,:), ...
    HCGp_WTstddev_clear(5,:));

HCGp_WT_mean_clear_horz=horzcat(...
    HCGp_WT_mean_clear(1,:), HCGp_WT_mean_clear (2,:), ...
    HCGp_WT_mean_clear(3,:), HCGp_WT_mean_clear (4,:), ...
    HCGp_WT_mean_clear(5,:));

for icond=1:5
HCGp_WTstddev_noise(icond,:)=horzcat(...
    GpStd_WT_HC(1).data(icond+5).data, GpStd_WT_HC(2).data(icond+5).data, ...
    GpStd_WT_HC(3).data(icond+5).data, GpStd_WT_HC(4).data(icond+5).data); 
%     , ...
%     GpStd_WT_HC(5).data(icond+5).data, GpStd_WT_HC(6).data(icond+5).data, ...
%     GpStd_WT_HC(7).data(icond+5).data, GpStd_WT_HC(8).data(icond+5).data, ...
%     GpStd_WT_HC(9).data(icond+5).data, GpStd_WT_HC(10).data(icond+5).data, ...
%     GpStd_WT_HC(11).data(icond+5).data);
HCGp_WT_mean_noise(icond,:)=horzcat(...
    GpMean_WT_HC(1).data(icond+5).data, GpMean_WT_HC(2).data(icond+5).data, ...
    GpMean_WT_HC(3).data(icond+5).data, GpMean_WT_HC(4).data(icond+5).data); 

end

HCGp_WTstddev_noise_horz=horzcat(...
    HCGp_WTstddev_noise(1,:), HCGp_WTstddev_noise (2,:), ...
    HCGp_WTstddev_noise(3,:), HCGp_WTstddev_noise (4,:), ...
    HCGp_WTstddev_noise(5,:));

HCGp_WT_mean_noise_horz=horzcat(...
    HCGp_WT_mean_noise(1,:), HCGp_WT_mean_noise (2,:), ...
    HCGp_WT_mean_noise(3,:), HCGp_WT_mean_noise (4,:), ...
    HCGp_WT_mean_noise(5,:));

% WT stdev anova
anova_data_WTstdev=[HCGp_WTstddev_clear_horz, HCGp_WTstddev_noise_horz, PatGp_WTstddev_clear_horz, PatGp_WTstddev_noise_horz];
anova_data_WTmean=[HCGp_WT_mean_clear_horz, HCGp_WT_mean_noise_horz, PatGp_WT_mean_clear_horz, PatGp_WT_mean_noise_horz];

HC_gp=length(HCGp_WTstddev_clear_horz);
PAT_gp=length(PatGp_WTstddev_clear_horz);
%create subject group
test=ones(1,HC_gp*2);
test2=ones(1,PAT_gp*2);
test2=test2*2;
subjectgroup=[test test2];

%create condition group
condition = cell(1,length(anova_data_WTstdev));
for i=1:HC_gp
    condition{i}='clear';
end
for i=HC_gp+1:HC_gp*2
    condition{i}='noise';
end
for i=HC_gp*2+1:HC_gp*2+PAT_gp
    condition{i}='clear';
end
for i=HC_gp*2+PAT_gp+1:(HC_gp*2)+(PAT_gp*2)
    condition{i}='noise';
end
condition=condition';

group1=[subjectgroup];
group2=[condition];

% p= anovan(anova_data_WTstdev,{group1 group2},'model','interaction')
% [pvals,tbl,stats] = anovan(anova_data_WTstdev,{group1 group2},'random',1, 'model','interaction','varnames',{'subjectgroup' 'condition'});
% [pvals,tbl,stats] = anovan(anova_data_WTstdev,{group1 group2}, 'model','interaction','varnames',{'subjectgroup' 'condition'});


STATS.anova_data_WTstdev= anovan(anova_data_WTstdev,{group1 group2},'random',1, 'model','interaction','varnames',{'subjectgroup' 'condition'});
STATS.anova_data_WTmean= anovan(anova_data_WTmean,{group1 group2},'random',1, 'model','interaction','varnames',{'subjectgroup' 'condition'});
%% ttests
ttest(HCGp_WTstddev_clear_horz, HCGp_WTstddev_noise_horz)
ttest(PatGp_WTstddev_clear_horz, PatGp_WTstddev_noise_horz)
ttest2(HCGp_WTstddev_clear_horz, PatGp_WTstddev_clear_horz)
ttest2(HCGp_WTstddev_noise_horz, PatGp_WTstddev_noise_horz)

%plot this:
figure
y_pitch2=[nanmean(HCGp_WTstddev_clear_horz) nanmean(HCGp_WTstddev_noise_horz); ...
          nanmean(PatGp_WTstddev_clear_horz) nanmean(PatGp_WTstddev_noise_horz)];
errY2 = [nanstd(HCGp_WTstddev_clear_horz)/sqrt(goodtrials_HC_clear) nanstd(HCGp_WTstddev_noise_horz)/sqrt(goodtrials_HC_noise); ...
          nanstd(PatGp_WTstddev_clear_horz)/sqrt(goodtrials_pat_clear) nanstd(PatGp_WTstddev_noise_horz)/sqrt(goodtrials_pat_noise)];            
h = barwitherr(errY2, y_pitch2);% Plot with errorbars
set(gca,'XTickLabel',{'HCs','Patients'})
ylabel('mean stdev of distance from low pass filt')
set(h(1),'FaceColor','k');
set(h(2),'FaceColor','w');
title(sprintf('Group mean variability in pitch tracking'));
axis([0 3 0 35])
legend('clear', 'noise')
goodplot
print(gcf, '-dpdf', '-r150', '/Users/zagnew/Desktop/meanWTstdvaribility.pdf');





